[workspace]
members = ["bin", "core", "db", "net", "substrate"]

[package]
name = "ipfs-embed"
version = "0.5.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "small embeddable ipfs implementation"
repository = "https://github.com/ipfs-rust/ipfs-embed"

[dependencies]
async-std = "1.6.3"
async-trait = "0.1.40"
futures = "0.3.5"
ipfs-embed-core = { path = "core" }
ipfs-embed-db = { version = "0.5.0", path = "db" }
ipfs-embed-net = { path = "net" }
ipfs-embed-substrate = { path = "substrate" }
libipld = { version = "0.5.1", default-features = false }
log = "0.4.11"

[dev-dependencies]
async-log = "2.0.0"
criterion = "0.3.3"
env_logger = "0.7.1"
#ipld-collections = "0.2.0"
model = "0.1.2"
tempdir = "0.3.7"

[profile.release]
debug = true

[[bench]]
name = "list"
harness = false

[patch.crates-io]
sc-network = { path = "../substrate/client/network" }
sp-runtime = { path = "../substrate/primitives/runtime" }
