[package]
name = "ipfs-embed"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }
futures = "0.3.4"
libipld-core = { path = "../rust-ipld/core" }
libp2p = "0.18.1"
libp2p-bitswap = "0.1.1"
log = "0.4.8"
sled = { git = "https://github.com/spacejam/sled" } # waiting for 0.32
thiserror = "1.0.16"

[dev-dependencies]
env_logger = "0.7.1"
tempdir = "0.3.7"
