[package]
name = "ipfs-embed"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }
libipld = { version = "0.1.0", default-features = false }
libp2p-bitswap = "0.2.0"
log = "0.4.8"
sled = { git = "https://github.com/spacejam/sled" } # waiting for 0.32
thiserror = "1.0.16"

[dependencies.libp2p]
version = "0.18.1"
default-features = false
features = ["kad", "mdns", "ping", "secio", "tcp", "yamux"]

[dev-dependencies]
env_logger = "0.7.1"
ipld-block-builder = "0.1.0"
tempdir = "0.3.7"

[patch.crates-io]
cid = { path = "../rust-cid" }
ipld-block-builder = { path = "../ipld-block-builder" }
libipld = { path = "../rust-ipld" }
libp2p-core = { path = "../rust-libp2p/core" }
libp2p-swarm = { path = "../rust-libp2p/swarm" }
libp2p-bitswap = { path = "../libp2p-bitswap" }
libp2p = { path = "../rust-libp2p" }
multihash = { path = "../rust-multihash" }
