[package]
name = "ipfs-embed"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }
libipld = { version = "0.2.0", default-features = false }
libp2p-bitswap = "0.3.0"
log = "0.4.8"
sled = { git = "https://github.com/spacejam/sled" } # waiting for 0.32
thiserror = "1.0.16"

[dependencies.libp2p]
version = "0.18.1"
default-features = false
features = ["kad", "mdns", "ping", "secio", "tcp", "yamux"]

[dev-dependencies]
async-log = "1.1.0"
disco = "0.1.0"
env_logger = "0.7.1"
ipld-block-builder = "0.1.0"
tempdir = "0.3.7"
